# Generated by Django 5.1.7 on 2025-04-29 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produits', '0004_alter_produits_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ventes_jour', models.IntegerField(default=0)),
                ('total_vente_jour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ventes_mois', models.IntegerField(default=0)),
                ('total_vente_mois', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.produits')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('produit', 'date')},
            },
        ),
    ]
