# Generated by Django 5.1.7 on 2025-05-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Statistiques', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistiqueproduit',
            old_name='ventes_jour',
            new_name='nbr_vente_par_jour',
        ),
        migrations.RenameField(
            model_name='statistiqueproduit',
            old_name='ventes_mois',
            new_name='nbr_vente_par_mois',
        ),
    ]
