# Generated by Django 4.2 on 2025-04-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0004_alter_produits_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='image',
        ),
        migrations.AlterField(
            model_name='produits',
            name='category',
            field=models.ForeignKey(choices=[('prescription', 'Prescription Medications (Rx)'), ('otc', 'Over-the-Counter (OTC) Medicines'), ('vitamins', 'Vitamins & Supplements'), ('personal_care', 'Personal Care & Hygiene'), ('baby_care', 'Baby & Mother Care'), ('devices', 'Medical Devices & Equipment'), ('first_aid', 'First Aid & Emergency Supplies'), ('herbal', 'Herbal & Natural Products'), ('sexual_health', 'Sexual Health & Family Planning')], on_delete=django.db.models.deletion.CASCADE, to='Produits.categories'),
        ),
    ]
