# Generated by Django 5.1.6 on 2025-04-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0005_remove_produits_image_alter_produits_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.categories'),
        ),
    ]
